package justcode.com.common.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import justcode.com.common.db.entity.record.RecordEntity;
import justcode.com.common.db.entity.record.RecordEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordEntityDaoConfig;

    private final RecordEntityDao recordEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordEntityDaoConfig = daoConfigMap.get(RecordEntityDao.class).clone();
        recordEntityDaoConfig.initIdentityScope(type);

        recordEntityDao = new RecordEntityDao(recordEntityDaoConfig, this);

        registerDao(RecordEntity.class, recordEntityDao);
    }
    
    public void clear() {
        recordEntityDaoConfig.clearIdentityScope();
    }

    public RecordEntityDao getRecordEntityDao() {
        return recordEntityDao;
    }

}
