package justcode.com.common.db.entity.record;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import justcode.com.common.db.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECORD_ENTITY".
*/
public class RecordEntityDao extends AbstractDao<RecordEntity, Long> {

    public static final String TABLENAME = "RECORD_ENTITY";

    /**
     * Properties of entity RecordEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Connent = new Property(2, String.class, "connent", false, "CONNENT");
        public final static Property TimeStr = new Property(3, String.class, "timeStr", false, "TIME_STR");
        public final static Property Date = new Property(4, long.class, "date", false, "DATE");
        public final static Property ImpPath = new Property(5, String.class, "impPath", false, "IMP_PATH");
    }


    public RecordEntityDao(DaoConfig config) {
        super(config);
    }
    
    public RecordEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"CONNENT\" TEXT," + // 2: connent
                "\"TIME_STR\" TEXT," + // 3: timeStr
                "\"DATE\" INTEGER NOT NULL ," + // 4: date
                "\"IMP_PATH\" TEXT);"); // 5: impPath
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecordEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String connent = entity.getConnent();
        if (connent != null) {
            stmt.bindString(3, connent);
        }
 
        String timeStr = entity.getTimeStr();
        if (timeStr != null) {
            stmt.bindString(4, timeStr);
        }
        stmt.bindLong(5, entity.getDate());
 
        String impPath = entity.getImpPath();
        if (impPath != null) {
            stmt.bindString(6, impPath);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecordEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String connent = entity.getConnent();
        if (connent != null) {
            stmt.bindString(3, connent);
        }
 
        String timeStr = entity.getTimeStr();
        if (timeStr != null) {
            stmt.bindString(4, timeStr);
        }
        stmt.bindLong(5, entity.getDate());
 
        String impPath = entity.getImpPath();
        if (impPath != null) {
            stmt.bindString(6, impPath);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public RecordEntity readEntity(Cursor cursor, int offset) {
        RecordEntity entity = new RecordEntity( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // connent
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // timeStr
            cursor.getLong(offset + 4), // date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // impPath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecordEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setConnent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTimeStr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDate(cursor.getLong(offset + 4));
        entity.setImpPath(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RecordEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RecordEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RecordEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
